### PR TITLE
Expose adminuser and connection information as outputs

### PR DESCRIPTION
**Pull request by shemau**
### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by toddgiguere — APPROVED** [review]

**Comment by ocofaigh** [comment]
Pipeline failed with:
```
Error: mError: [ERROR] Error waiting for database (crn:v1:bluemix:public:databases-for-mysql:eu-de:a%2Fabac0df06b644a9cabc6e44f55b3880e:e2cb8cd7-cef2-46c1-84f3-d32108d74eee::) configuration update task to complete: [Error] Database Task failed
│ 
│   with module.mysql_db.ibm_database.mysql_db,
│   on ../../main.tf line 52, in resource "ibm_database" "mysql_db":
│   52: resource "ibm_database" "mysql_db" {
│ 
╵}
```

Possibly backend issue and unrelated to code? I'll re-run pipeline and see..

**Pull request merged**
